### ISSUE TITLE
images

### ISSUE THREAD

**Issue by TiceRex** [black-sheep-dev/sailfish-os-torrents#1]
Hi,
Attached please find two torrents for old Sailfish OS versions.
(Sorry, I don't know how to create a pull request...)
Regards,
TiceRex

[Old_Sailfish_Images_torrents.zip](https://github.com/black-sheep-dev/sailfish-os-torrents/files/6015348/Old_Sailfish_Images_torrents.zip)

**Comment by black-sheep-dev** [comment]
Thanks! I added them to the repo.
